// Package hello provides marshaller for entities.
//
// Code generated by github.com/outofforest/proton DO NOT EDIT.
package hello

import (
	"reflect"

	"github.com/outofforest/magma/gossip/wire"
	"github.com/outofforest/magma/types"
	"github.com/outofforest/proton"
	"github.com/outofforest/proton/helpers"
	"github.com/pkg/errors"
)

const (
	id1 uint64 = iota + 1
	id0
)

var _ proton.Marshaller = Marshaller{}

// NewMarshaller creates marshaller.
func NewMarshaller() Marshaller {
	return Marshaller{}
}

// Marshaller marshals and unmarshals messages.
type Marshaller struct {
}

// Messages returns list of the message types supported by marshaller.
func (m Marshaller) Messages() []any {
	return []any{
		wire.Hello{},
		wire.HelloResponse{},
	}
}

// ID returns ID of message type.
func (m Marshaller) ID(msg any) (uint64, error) {
	switch msg.(type) {
	case *wire.Hello:
		return id1, nil
	case *wire.HelloResponse:
		return id0, nil
	default:
		return 0, errors.Errorf("unknown message type %T", msg)
	}
}

// Size computes the size of marshalled message.
func (m Marshaller) Size(msg any) (uint64, error) {
	switch msg2 := msg.(type) {
	case *wire.Hello:
		return size1(msg2), nil
	case *wire.HelloResponse:
		return size0(msg2), nil
	default:
		return 0, errors.Errorf("unknown message type %T", msg)
	}
}

// Marshal marshals message.
func (m Marshaller) Marshal(msg any, buf []byte) (retID, retSize uint64, retErr error) {
	defer helpers.RecoverMarshal(&retErr)

	switch msg2 := msg.(type) {
	case *wire.Hello:
		return id1, marshal1(msg2, buf), nil
	case *wire.HelloResponse:
		return id0, marshal0(msg2, buf), nil
	default:
		return 0, 0, errors.Errorf("unknown message type %T", msg)
	}
}

// Unmarshal unmarshals message.
func (m Marshaller) Unmarshal(id uint64, buf []byte) (retMsg any, retSize uint64, retErr error) {
	defer helpers.RecoverUnmarshal(&retErr)

	switch id {
	case id1:
		msg := &wire.Hello{}
		return msg, unmarshal1(msg, buf), nil
	case id0:
		msg := &wire.HelloResponse{}
		return msg, unmarshal0(msg, buf), nil
	default:
		return nil, 0, errors.Errorf("unknown ID %d", id)
	}
}

// IsPatchNeeded checks if non-empty patch exists.
func (m Marshaller) IsPatchNeeded(msgDst, msgSrc any) (bool, error) {
	switch msg2 := msgDst.(type) {
	case *wire.Hello:
		return isPatchNeeded1(msg2, msgSrc.(*wire.Hello)), nil
	case *wire.HelloResponse:
		return isPatchNeeded0(msg2, msgSrc.(*wire.HelloResponse)), nil
	default:
		return false, errors.Errorf("unknown message type %T", msgDst)
	}
}

// MakePatch creates a patch.
func (m Marshaller) MakePatch(msgDst, msgSrc any, buf []byte) (retID, retSize uint64, retErr error) {
	defer helpers.RecoverMakePatch(&retErr)

	switch msg2 := msgDst.(type) {
	case *wire.Hello:
		return id1, makePatch1(msg2, msgSrc.(*wire.Hello), buf), nil
	case *wire.HelloResponse:
		return id0, makePatch0(msg2, msgSrc.(*wire.HelloResponse), buf), nil
	default:
		return 0, 0, errors.Errorf("unknown message type %T", msgDst)
	}
}

// ApplyPatch applies patch.
func (m Marshaller) ApplyPatch(msg any, buf []byte) (retSize uint64, retErr error) {
	defer helpers.RecoverApplyPatch(&retErr)

	switch msg2 := msg.(type) {
	case *wire.Hello:
		return applyPatch1(msg2, buf), nil
	case *wire.HelloResponse:
		return applyPatch0(msg2, buf), nil
	default:
		return 0, errors.Errorf("unknown message type %T", msg)
	}
}

func size0(m *wire.HelloResponse) uint64 {
	var n uint64 = 1
	{
		// Error

		{
			l := uint64(len(m.Error))
			helpers.UInt64Size(l, &n)
			n += l
		}
	}
	return n
}

func marshal0(m *wire.HelloResponse, b []byte) uint64 {
	var o uint64
	{
		// Error

		{
			l := uint64(len(m.Error))
			helpers.UInt64Marshal(l, b, &o)
			copy(b[o:o+l], m.Error)
			o += l
		}
	}

	return o
}

func unmarshal0(m *wire.HelloResponse, b []byte) uint64 {
	var o uint64
	{
		// Error

		{
			var l uint64
			helpers.UInt64Unmarshal(&l, b, &o)
			if l > 0 {
				m.Error = string(b[o : o+l])
				o += l
			}
		}
	}

	return o
}

func isPatchNeeded0(m, mSrc *wire.HelloResponse) bool {
	{
		// Error

		if !reflect.DeepEqual(m.Error, mSrc.Error) {
			return true
		}

	}

	return false
}

func makePatch0(m, mSrc *wire.HelloResponse, b []byte) uint64 {
	var o uint64 = 1
	{
		// Error

		if reflect.DeepEqual(m.Error, mSrc.Error) {
			b[0] &= 0xFE
		} else {
			b[0] |= 0x01
			{
				l := uint64(len(m.Error))
				helpers.UInt64Marshal(l, b, &o)
				copy(b[o:o+l], m.Error)
				o += l
			}
		}
	}

	return o
}

func applyPatch0(m *wire.HelloResponse, b []byte) uint64 {
	var o uint64 = 1
	{
		// Error

		if b[0]&0x01 != 0 {
			{
				var l uint64
				helpers.UInt64Unmarshal(&l, b, &o)
				if l > 0 {
					m.Error = string(b[o : o+l])
					o += l
				}
			}
		}
	}

	return o
}

func size1(m *wire.Hello) uint64 {
	var n uint64 = 4
	{
		// ServerID

		{
			l := uint64(len(m.ServerID))
			helpers.UInt64Size(l, &n)
			n += l
		}
	}
	{
		// PartitionID

		{
			l := uint64(len(m.PartitionID))
			helpers.UInt64Size(l, &n)
			n += l
		}
	}
	{
		// Namespace

		{
			l := uint64(len(m.Namespace))
			helpers.UInt64Size(l, &n)
			n += l
		}
	}
	return n
}

func marshal1(m *wire.Hello, b []byte) uint64 {
	var o uint64
	{
		// ServerID

		{
			l := uint64(len(m.ServerID))
			helpers.UInt64Marshal(l, b, &o)
			copy(b[o:o+l], m.ServerID)
			o += l
		}
	}
	{
		// PartitionID

		{
			l := uint64(len(m.PartitionID))
			helpers.UInt64Marshal(l, b, &o)
			copy(b[o:o+l], m.PartitionID)
			o += l
		}
	}
	{
		// Namespace

		{
			l := uint64(len(m.Namespace))
			helpers.UInt64Marshal(l, b, &o)
			copy(b[o:o+l], m.Namespace)
			o += l
		}
	}
	{
		// Channel

		b[o] = byte(m.Channel)
		o++
	}

	return o
}

func unmarshal1(m *wire.Hello, b []byte) uint64 {
	var o uint64
	{
		// ServerID

		{
			var l uint64
			helpers.UInt64Unmarshal(&l, b, &o)
			if l > 0 {
				m.ServerID = types.ServerID(b[o : o+l])
				o += l
			}
		}
	}
	{
		// PartitionID

		{
			var l uint64
			helpers.UInt64Unmarshal(&l, b, &o)
			if l > 0 {
				m.PartitionID = types.PartitionID(b[o : o+l])
				o += l
			}
		}
	}
	{
		// Namespace

		{
			var l uint64
			helpers.UInt64Unmarshal(&l, b, &o)
			if l > 0 {
				m.Namespace = wire.Namespace(b[o : o+l])
				o += l
			}
		}
	}
	{
		// Channel

		m.Channel = wire.Channel(b[o])
		o++
	}

	return o
}

func isPatchNeeded1(m, mSrc *wire.Hello) bool {
	{
		// ServerID

		if !reflect.DeepEqual(m.ServerID, mSrc.ServerID) {
			return true
		}

	}
	{
		// PartitionID

		if !reflect.DeepEqual(m.PartitionID, mSrc.PartitionID) {
			return true
		}

	}
	{
		// Namespace

		if !reflect.DeepEqual(m.Namespace, mSrc.Namespace) {
			return true
		}

	}
	{
		// Channel

		if !reflect.DeepEqual(m.Channel, mSrc.Channel) {
			return true
		}

	}

	return false
}

func makePatch1(m, mSrc *wire.Hello, b []byte) uint64 {
	var o uint64 = 1
	{
		// ServerID

		if reflect.DeepEqual(m.ServerID, mSrc.ServerID) {
			b[0] &= 0xFE
		} else {
			b[0] |= 0x01
			{
				l := uint64(len(m.ServerID))
				helpers.UInt64Marshal(l, b, &o)
				copy(b[o:o+l], m.ServerID)
				o += l
			}
		}
	}
	{
		// PartitionID

		if reflect.DeepEqual(m.PartitionID, mSrc.PartitionID) {
			b[0] &= 0xFD
		} else {
			b[0] |= 0x02
			{
				l := uint64(len(m.PartitionID))
				helpers.UInt64Marshal(l, b, &o)
				copy(b[o:o+l], m.PartitionID)
				o += l
			}
		}
	}
	{
		// Namespace

		if reflect.DeepEqual(m.Namespace, mSrc.Namespace) {
			b[0] &= 0xFB
		} else {
			b[0] |= 0x04
			{
				l := uint64(len(m.Namespace))
				helpers.UInt64Marshal(l, b, &o)
				copy(b[o:o+l], m.Namespace)
				o += l
			}
		}
	}
	{
		// Channel

		if reflect.DeepEqual(m.Channel, mSrc.Channel) {
			b[0] &= 0xF7
		} else {
			b[0] |= 0x08
			b[o] = byte(m.Channel)
			o++
		}
	}

	return o
}

func applyPatch1(m *wire.Hello, b []byte) uint64 {
	var o uint64 = 1
	{
		// ServerID

		if b[0]&0x01 != 0 {
			{
				var l uint64
				helpers.UInt64Unmarshal(&l, b, &o)
				if l > 0 {
					m.ServerID = types.ServerID(b[o : o+l])
					o += l
				}
			}
		}
	}
	{
		// PartitionID

		if b[0]&0x02 != 0 {
			{
				var l uint64
				helpers.UInt64Unmarshal(&l, b, &o)
				if l > 0 {
					m.PartitionID = types.PartitionID(b[o : o+l])
					o += l
				}
			}
		}
	}
	{
		// Namespace

		if b[0]&0x04 != 0 {
			{
				var l uint64
				helpers.UInt64Unmarshal(&l, b, &o)
				if l > 0 {
					m.Namespace = wire.Namespace(b[o : o+l])
					o += l
				}
			}
		}
	}
	{
		// Channel

		if b[0]&0x08 != 0 {
			m.Channel = wire.Channel(b[o])
			o++
		}
	}

	return o
}
